In [1]:
import numpy as np

In [7]:
def calc_ff(time, trimp, tau):
    return np.convolve(np.exp(-time/tau), trimp)

In [8]:
time = np.arange(10)
trimp = np.array([10,0,0,20,20,0,0,10,10,0])

In [9]:
#dt = np.diff(time, prepend=time[0])
np.convolve(np.exp(-time/15), trimp)

array([10.        ,  9.35506985,  8.75173319, 28.18730753, 46.36942308,
       43.37891919, 40.5812819 , 47.96407268, 54.87072502, 51.33194653,
       42.88722335, 40.12129701, 37.5337536 , 24.84474629, 12.97409131,
       12.13735305, 11.35457856,  5.48811636,  0.        ])

In [13]:
np.convolve(np.exp(-time/15), trimp, 'full').shape

(19,)

In [14]:
np.exp(-time/15)

array([1.        , 0.93550699, 0.87517332, 0.81873075, 0.76592834,
       0.71653131, 0.67032005, 0.62708909, 0.58664622, 0.54881164])

In [15]:
trimp

array([10,  0,  0, 20, 20,  0,  0, 10, 10,  0])

In [19]:
trimp = np.array([0] + [100] + [0]*17)
time = np.arange(trimp.size)
calc_ff(time, trimp, 10)

array([  0.        , 100.        ,  90.4837418 ,  81.87307531,
        74.08182207,  67.0320046 ,  60.65306597,  54.88116361,
        49.65853038,  44.93289641,  40.65696597,  36.78794412,
        33.28710837,  30.11942119,  27.2531793 ,  24.65969639,
        22.31301601,  20.1896518 ,  18.26835241,  16.52988882,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ])